workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - credentials
    scripts:
      - name: Create credentials files from environment variables
        script: |
          set -e
          mkdir -p assets
          echo $GOOGLE_CREDENTIALS_JSON > assets/credentials.json
          echo $GOOGLE_CREDENTIALS_JSON > assets/jwenochs-subattendance-0203df541a27.json
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ipa # Changed from ios --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa

signing:
  ios:
    distribution_type: app_store
    bundle_id: com.dlerhetal.subattendanceapp
    certificate_id: sub_attendance
    provisioning_profile_id: sub_attendance
